name: Blum bot docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'corretto'
        architecture: x64

    - name: Define variables
      run: echo "version=$(grep -oP 'version\s*=\s*"\K[0-9.]+' build.gradle.kts)" >> $GITHUB_ENV

    - name: Build the app
      run: ./gradlew installDist

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/anisovaleksey/blumbot:${{ env.version }}
          ghcr.io/anisovaleksey/blumbot:latest
